# Generated by Django 6.0.1 on 2026-01-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery')], default='cod', max_length=20),
        ),
    ]
